validate:

  - name: Courses
    schema: schemas/course.rx.yml
    data: data/courses/*/course.yml

  - name: Course Terms
    schema: schemas/course-term.rx.yml
    data: data/courses/*/term-*.yml

  - name: Subjects
    schema: schemas/subject.rx.yml
    data: data/subjects/*.yml

  - name: Instructors
    schema: schemas/instructor.rx.yml
    data: data/instructors/*.yml
